/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finance_new;

/**
 *
 * @author PC
 */
public class NewJPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel2
     */
    public NewJPanel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        txt_payments_time = new javax.swing.JTextField();
        cmd_payments_out = new javax.swing.JButton();
        cmd_payments_in = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        txt_search_payments_id = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        txt_payments_amount = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        but_payments_patient = new javax.swing.JRadioButton();
        but_payments_salary = new javax.swing.JRadioButton();
        but_payments_purchase = new javax.swing.JRadioButton();
        but_payments_bill_payments = new javax.swing.JRadioButton();
        but_payments_other = new javax.swing.JRadioButton();
        txt_payments_sub_category = new javax.swing.JComboBox<>();
        jLabel54 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_payments_booking_id = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_payments_staff_id = new javax.swing.JTextField();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        txt_payments_id = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jButton49 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbl_payments_search = new javax.swing.JTable();
        jLabel67 = new javax.swing.JLabel();
        txt_payments_category = new javax.swing.JComboBox<>();
        jLabel68 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbl_payments = new javax.swing.JTable();

        jPanel14.setBackground(new java.awt.Color(153, 153, 153));
        jPanel14.setBorder(new javax.swing.border.MatteBorder(null));

        txt_payments_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_payments_timeActionPerformed(evt);
            }
        });

        cmd_payments_out.setText("Spend");
        cmd_payments_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_payments_outActionPerformed(evt);
            }
        });

        cmd_payments_in.setText("Income");
        cmd_payments_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_payments_inActionPerformed(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "PAYMENT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 3, 11), new java.awt.Color(0, 102, 204))); // NOI18N

        jLabel37.setText("Payment ID");

        txt_search_payments_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search_payments_idActionPerformed(evt);
            }
        });
        txt_search_payments_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search_payments_idKeyReleased(evt);
            }
        });

        jLabel52.setText(":");

        jLabel55.setText("Amount");

        jLabel66.setText(":");

        jPanel16.setBackground(new java.awt.Color(153, 153, 153));

        jLabel53.setText("Category");

        but_payments_patient.setBackground(new java.awt.Color(153, 153, 153));
        but_payments_patient.setText("Patient");
        but_payments_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_payments_patientActionPerformed(evt);
            }
        });
        but_payments_patient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                but_payments_patientKeyPressed(evt);
            }
        });

        but_payments_salary.setBackground(new java.awt.Color(153, 153, 153));
        but_payments_salary.setText("Salary");
        but_payments_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_payments_salaryActionPerformed(evt);
            }
        });

        but_payments_purchase.setBackground(new java.awt.Color(153, 153, 153));
        but_payments_purchase.setText("Purchase");

        but_payments_bill_payments.setBackground(new java.awt.Color(153, 153, 153));
        but_payments_bill_payments.setText("Bill Payments");

        but_payments_other.setBackground(new java.awt.Color(153, 153, 153));
        but_payments_other.setText("Other");

        txt_payments_sub_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        jLabel54.setText("Sub Category");

        jLabel12.setText("Booking ID");

        txt_payments_booking_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_payments_booking_idActionPerformed(evt);
            }
        });

        jLabel13.setText("Staff ID");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(but_payments_salary)
                            .addComponent(but_payments_patient)
                            .addComponent(jLabel53))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54)
                            .addComponent(txt_payments_sub_category, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(but_payments_other)
                            .addComponent(but_payments_purchase)
                            .addComponent(but_payments_bill_payments))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txt_payments_booking_id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_payments_staff_id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_payments_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_payments_salary))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_payments_sub_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(but_payments_purchase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_payments_bill_payments)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_payments_other)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_payments_booking_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_payments_staff_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton46.setText("Update In");
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });

        jButton47.setText("Delete");
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });

        jButton48.setText("Reset");
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });

        txt_payments_id.setBackground(new java.awt.Color(255, 255, 255));
        txt_payments_id.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)));
        txt_payments_id.setOpaque(true);

        jLabel11.setText("Search");

        jLabel56.setText(":");

        jButton49.setText("Update Out");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });

        jButton9.setText("Report");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel66)
                        .addGap(18, 18, 18)
                        .addComponent(txt_payments_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_search_payments_id, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_payments_id, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton49, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search_payments_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel56)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel37)
                        .addComponent(jLabel52))
                    .addComponent(txt_payments_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel55)
                            .addComponent(txt_payments_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel66)))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jButton46)
                        .addGap(18, 18, 18)
                        .addComponent(jButton49)
                        .addGap(18, 18, 18)
                        .addComponent(jButton47)
                        .addGap(18, 18, 18)
                        .addComponent(jButton48)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl_payments_search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_payments_search.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Payment ID", "Sub category", "Date", "Amount_In", "Amount_Out"
            }
        ));
        jScrollPane7.setViewportView(tbl_payments_search);

        jLabel67.setText("Category");

        txt_payments_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Patient", "Salary", "Purchase", "Bill Payments", "Other" }));
        txt_payments_category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_payments_categoryMousePressed(evt);
            }
        });
        txt_payments_category.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_payments_categoryPropertyChange(evt);
            }
        });

        jLabel68.setText(":");

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel68)
                        .addGap(18, 18, 18)
                        .addComponent(txt_payments_category, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67)
                    .addComponent(txt_payments_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel68)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbl_payments.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_payments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Payment ID", "Category", "Sub Category", "Income", "Spend", "Date", "Staff ID", "Booking ID"
            }
        ));
        jScrollPane8.setViewportView(tbl_payments);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(cmd_payments_in, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_payments_time, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmd_payments_out, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_payments_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmd_payments_in, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmd_payments_out, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1163, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_payments_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_payments_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_payments_timeActionPerformed

    private void cmd_payments_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_payments_outActionPerformed

        String category ="";
        if(but_payments_patient.isSelected())
        {
            category="Patient";

        }
        else if(but_payments_salary.isSelected())
        {
            category="Salary";
        }
        else if(but_payments_purchase.isSelected())
        {
            category="Purchase";
        }
        else if(but_payments_bill_payments.isSelected())
        {
            category="Bill Payments";
        }
        else if(but_payments_other.isSelected())
        {
            category="Other";
        }

        String sub_category=txt_payments_sub_category.getSelectedItem().toString();

        double amount_out=Double.parseDouble(txt_payments_amount.getText());

        Format formatter = new SimpleDateFormat("yyyy-MM-dd");
        String date = formatter.format(txt_payments_date.getDate());

        try{
            pst=conn.prepareStatement("Insert into payments values (?, ?, ?, ?, ?, ?, ?, ?)");

            pst.setInt(1, payments_id);
            pst.setString(2,category);
            pst.setString(3,String.valueOf(sub_category));
            pst.setNull(4, java.sql.Types.DOUBLE);
            pst.setDouble(5, amount_out);
            pst.setString(6, date);
            pst.setNull(7, java.sql.Types.INTEGER);
            pst.setNull(8, java.sql.Types.INTEGER);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null,"Inserted Successfully");
            dtm.addRow(new Object[]{String.valueOf(payments_id),category,sub_category,amount_out,date});
            ++payments_id;

        }
        catch (SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);
        }
        showTableData1();
    }//GEN-LAST:event_cmd_payments_outActionPerformed

    private void cmd_payments_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_payments_inActionPerformed
        // TODO add your handling code here:

        String category ="";
        if(but_payments_patient.isSelected())
        {
            category="Patient";

        }
        else if(but_payments_salary.isSelected())
        {
            category="Salary";
        }
        else if(but_payments_purchase.isSelected())
        {
            category="Purchase";
        }
        else if(but_payments_bill_payments.isSelected())
        {
            category="Bill Payments";
        }
        else if(but_payments_other.isSelected())
        {
            category="Other";
        }

        String sub_category=txt_payments_sub_category.getSelectedItem().toString();

        double amount_in=Double.parseDouble(txt_payments_amount.getText());

        Format formatter = new SimpleDateFormat("yyyy-MM-dd");
        String date = formatter.format(txt_payments_date.getDate());

        try{
            pst=conn.prepareStatement("Insert into payments values (?, ?, ?, ?, ?, ?, ?, ?)");

            pst.setInt(1, payments_id);
            pst.setString(2,category);
            pst.setString(3,String.valueOf(sub_category));
            pst.setDouble(4, amount_in);
            pst.setNull(5, java.sql.Types.DOUBLE);
            pst.setString(6, date);
            pst.setNull(7, java.sql.Types.INTEGER);
            pst.setNull(8, java.sql.Types.INTEGER);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null,"Inserted Successfully");

        }
        catch (SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);
        }
        txt_payments_id.setText(String.valueOf(payments_id));
        showTableData1();
    }//GEN-LAST:event_cmd_payments_inActionPerformed

    private void txt_search_payments_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search_payments_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search_payments_idActionPerformed

    private void txt_search_payments_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_payments_idKeyReleased
        // TODO add your handling code here:

        txt_payments_id.setVisible(false);

        if(txt_search_payments_id.getText().equals(""))
        {
            txt_payments_id.setVisible(true);
        }

        try{
            String sql = "select * from payments where payments_id = ?";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txt_search_payments_id.getText());

            ResultSet rs = pst.executeQuery();

            if(rs.next()){
                if(rs.getString("amount_in").equals(""))
                {
                    String add1 = rs.getString("amount_out");
                    txt_payments_amount.setText(add1);

                }
                else{

                    String add1 = rs.getString("amount_in");
                    txt_payments_amount.setText(add1);
                }

            }
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txt_search_payments_idKeyReleased

    private void but_payments_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_payments_patientActionPerformed
        // TODO add your handling code here:
        txt_payments_booking_id.setVisible(true);
        jLabel12.setVisible(true);
    }//GEN-LAST:event_but_payments_patientActionPerformed

    private void but_payments_patientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_but_payments_patientKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_but_payments_patientKeyPressed

    private void but_payments_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_payments_salaryActionPerformed
        // TODO add your handling code here:
        txt_payments_staff_id.setVisible(true);
        jLabel13.setVisible(true);
    }//GEN-LAST:event_but_payments_salaryActionPerformed

    private void txt_payments_booking_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_payments_booking_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_payments_booking_idActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        // TODO add your handling code here:

        String category ="";
        if(but_payments_patient.isSelected())
        {
            category="Patient";

        }
        else if(but_payments_salary.isSelected())
        {
            category="Salary";
        }
        else if(but_payments_purchase.isSelected())
        {
            category="Purchase";
        }
        else if(but_payments_bill_payments.isSelected())
        {
            category="Bill Payments";
        }
        else if(but_payments_other.isSelected())
        {
            category="Other";
        }

        String sub_category=txt_payments_sub_category.getSelectedItem().toString();

        double amount_in=Double.parseDouble(txt_payments_amount.getText());

        Format formatter = new SimpleDateFormat("yyyy-MM-dd");
        String date = formatter.format(txt_payments_date.getDate());

        try{
            st = conn.createStatement();
            String SQL = "Update payments SET "
            + "category='"+category+"',"
            + "sub_category='"+sub_category+"',"
            + "amount_in='"+amount_in+"',"

            + "date='"+date+"' WHERE payments_id Like "+txt_search_payments_id.getText();
            st.executeUpdate(SQL);

            JOptionPane.showMessageDialog(null,"Updated Successfully");

        }
        catch (SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        showTableData1();
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        // TODO add your handling code here:

        try{
            String sql = "DELETE from payments where payments_id = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_search_payments_id.getText());
            pst.execute();

            JOptionPane.showMessageDialog(null,"Deleted!");

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
        showTableData1();
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed

        txt_search_payments_id.setText("");
        txt_payments_id.setText("");
        txt_payments_booking_id.setText("");
        txt_payments_staff_id.setText("");
        txt_payments_amount.setText("");

    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        // TODO add your handling code here:

        String category ="";
        if(but_payments_patient.isSelected())
        {
            category="Patient";

        }
        else if(but_payments_salary.isSelected())
        {
            category="Salary";
        }
        else if(but_payments_purchase.isSelected())
        {
            category="Purchase";
        }
        else if(but_payments_bill_payments.isSelected())
        {
            category="Bill Payments";
        }
        else if(but_payments_other.isSelected())
        {
            category="Other";
        }

        String sub_category=txt_payments_sub_category.getSelectedItem().toString();

        double amount_out=Double.parseDouble(txt_payments_amount.getText());

        Format formatter = new SimpleDateFormat("yyyy-MM-dd");
        String date = formatter.format(txt_payments_date.getDate());

        try{
            st = conn.createStatement();
            String SQL = "Update payments SET "
            + "category='"+category+"',"
            + "sub_category='"+sub_category+"',"
            + "amount_out='"+amount_out+"',"

            + "date='"+date+"' WHERE payments_id Like "+txt_search_payments_id.getText();
            st.executeUpdate(SQL);

            JOptionPane.showMessageDialog(null,"Updated Successfully");

        }
        catch (SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        showTableData1();
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/yarlmothercare", "root", "");
            JasperDesign jdesign=JRXmlLoader.load("D:\\aaron\\New folder\\Yarl_Mother_Care\\src\\finance_management\\payments.jrxml");
            String query ="select * from payments";

            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);
            JasperReport jasp=JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint=JasperFillManager.fillReport(jasp,null,conn);
            JasperViewer.viewReport(jprint);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void txt_payments_categoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_payments_categoryMousePressed

    }//GEN-LAST:event_txt_payments_categoryMousePressed

    private void txt_payments_categoryPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_payments_categoryPropertyChange

    }//GEN-LAST:event_txt_payments_categoryPropertyChange

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        search_cat();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton but_payments_bill_payments;
    private javax.swing.JRadioButton but_payments_other;
    private javax.swing.JRadioButton but_payments_patient;
    private javax.swing.JRadioButton but_payments_purchase;
    private javax.swing.JRadioButton but_payments_salary;
    private javax.swing.JButton cmd_payments_in;
    private javax.swing.JButton cmd_payments_out;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable tbl_payments;
    private javax.swing.JTable tbl_payments_search;
    private javax.swing.JTextField txt_payments_amount;
    private javax.swing.JTextField txt_payments_booking_id;
    private javax.swing.JComboBox<String> txt_payments_category;
    private javax.swing.JLabel txt_payments_id;
    private javax.swing.JTextField txt_payments_staff_id;
    private javax.swing.JComboBox<String> txt_payments_sub_category;
    private javax.swing.JTextField txt_payments_time;
    private javax.swing.JTextField txt_search_payments_id;
    // End of variables declaration//GEN-END:variables
}
